/** Words for the "और" (More) screens. Hindi first; plain words a parent would say. Use with useL(). */
export const M = {
  back: { hi: "और", en: "More" },

  // menu rows
  notices: { hi: "सूचनाएँ", en: "Notices" },
  noticesSub: { hi: "स्कूल से आए सारे संदेश", en: "All messages from the school" },
  leave: { hi: "छुट्टी की अर्ज़ी", en: "Leave application" },
  leaveSub: { hi: "बच्चे की छुट्टी के लिए लिखें", en: "Ask leave for your child" },
  bus: { hi: "बस", en: "Bus" },
  busSub: { hi: "रूट, स्टॉप और ड्राइवर", en: "Route, stop and driver" },
  idCard: { hi: "आईडी कार्ड", en: "ID card" },
  idCardSub: { hi: "फ़ोन में बच्चे का पहचान पत्र", en: "Your child's ID on your phone" },
  result: { hi: "रिज़ल्ट", en: "Result" },
  resultSub: { hi: "परीक्षा के अंक और ग्रेड", en: "Exam marks and grades" },

  // notices
  noNotices: { hi: "अभी तक स्कूल से कोई संदेश नहीं आया।", en: "No messages from the school yet." },
  today: { hi: "आज", en: "Today" },
  yesterday: { hi: "कल", en: "Yesterday" },
  loadMore: { hi: "और पुराने संदेश", en: "Older messages" },

  // leave
  newLeave: { hi: "नई अर्ज़ी", en: "New application" },
  fromDate: { hi: "किस दिन से", en: "From" },
  toDate: { hi: "किस दिन तक", en: "To" },
  reason: { hi: "छुट्टी का कारण", en: "Reason for leave" },
  reasonHint: { hi: "जैसे: बुखार है, शादी में बाहर जा रहे हैं", en: "e.g. Has fever, going out of town for a wedding" },
  send: { hi: "अर्ज़ी भेजें", en: "Send application" },
  sending: { hi: "भेज रहे हैं…", en: "Sending…" },
  sent: { hi: "अर्ज़ी भेज दी गई। स्कूल जवाब देगा।", en: "Application sent. The school will answer." },
  past: { hi: "पिछली अर्ज़ियाँ", en: "Earlier applications" },
  noPast: { hi: "अभी तक कोई अर्ज़ी नहीं भेजी।", en: "No applications sent yet." },
  pending: { hi: "जवाब बाकी", en: "Waiting" },
  approved: { hi: "मंज़ूर", en: "Approved" },
  rejected: { hi: "नामंज़ूर", en: "Not approved" },
  by: { hi: "द्वारा", en: "by" },
  cancel: { hi: "अर्ज़ी वापस लें", en: "Cancel application" },
  cancelSure: { hi: "पक्का वापस लेनी है?", en: "Cancel this application?" },
  yesCancel: { hi: "हाँ, वापस लें", en: "Yes, cancel" },
  no: { hi: "नहीं", en: "No" },
  day: { hi: "दिन", en: "day" },
  days: { hi: "दिन", en: "days" },
  leaveRule: { hi: "एक बार में 30 दिन तक की छुट्टी। ज़्यादा के लिए स्कूल ऑफ़िस से मिलें।", en: "Up to 30 days at a time. For longer, please meet the school office." },
  leaveSetup: { hi: "छुट्टी की अर्ज़ी अभी चालू नहीं है। स्कूल ऑफ़िस से पूछें।", en: "Leave applications are not switched on yet. Please ask the school office." },
  badDates: { hi: "आख़िरी दिन पहले दिन से पहले नहीं हो सकता।", en: "The last day cannot be before the first day." },
  badReason: { hi: "छुट्टी का कारण लिखें।", en: "Write the reason for leave." },

  // bus
  noBus: { hi: "आपका बच्चा स्कूल बस से नहीं आता। बस लगवानी हो तो स्कूल ऑफ़िस से बात करें।", en: "Your child does not take the school bus. To start the bus, please talk to the school office." },
  route: { hi: "रूट", en: "Route" },
  stop: { hi: "आपका स्टॉप", en: "Your stop" },
  pickup: { hi: "बस आने का समय", en: "Pickup time" },
  vehicle: { hi: "गाड़ी नंबर", en: "Vehicle no." },
  driver: { hi: "ड्राइवर", en: "Driver" },
  conductor: { hi: "कंडक्टर", en: "Conductor" },
  callDriver: { hi: "ड्राइवर को कॉल करें", en: "Call the driver" },
  callConductor: { hi: "कंडक्टर को कॉल करें", en: "Call the conductor" },
  allStops: { hi: "रूट के सारे स्टॉप", en: "All stops on the route" },
  notSet: { hi: "अभी तय नहीं", en: "Not set yet" },
  noRoute: { hi: "बस का रूट अभी तय नहीं हुआ। स्कूल ऑफ़िस से पूछें।", en: "The bus route is not set yet. Please ask the school office." },

  // id card
  studentId: { hi: "छात्र पहचान पत्र", en: "Student ID card" },
  class: { hi: "कक्षा", en: "Class" },
  adm: { hi: "प्रवेश नं.", en: "Adm. no." },
  sr: { hi: "एस.आर. नं.", en: "SR no." },
  roll: { hi: "रोल नं.", en: "Roll no." },
  father: { hi: "पिता", en: "Father" },
  mother: { hi: "माता", en: "Mother" },
  dob: { hi: "जन्म तिथि", en: "Date of birth" },
  mobile: { hi: "मोबाइल", en: "Mobile" },
  address: { hi: "पता", en: "Address" },
  transport: { hi: "बस", en: "Bus" },
  session: { hi: "सत्र", en: "Session" },
  idNote: { hi: "स्कूल में दिखाने के लिए असली कार्ड ही मान्य है। कुछ गलत हो तो स्कूल ऑफ़िस को बताएँ।", en: "The printed card is the official one. If anything is wrong, please tell the school office." },

  // result
  noResult: { hi: "अभी कोई रिज़ल्ट नहीं आया। परीक्षा के अंक पक्के होने पर यहाँ दिखेंगे।", en: "No result yet. Marks show here once the school finalises them." },
  exam: { hi: "परीक्षा", en: "Exam" },
  subject: { hi: "विषय", en: "Subject" },
  marks: { hi: "अंक", en: "Marks" },
  grade: { hi: "ग्रेड", en: "Grade" },
  total: { hi: "कुल", en: "Total" },
  percent: { hi: "प्रतिशत", en: "Percent" },
  rank: { hi: "कक्षा में स्थान", en: "Class rank" },
  absent: { hi: "अनुपस्थित", en: "Absent" },
  notEntered: { hi: "बाकी", en: "Not in" },
  passed: { hi: "पास", en: "Passed" },
  needsWork: { hi: "इन विषयों में मेहनत चाहिए", en: "Needs improvement in" },
  incomplete: { hi: "अभी सभी अंक नहीं आए", en: "Not all marks are in yet" },
  attendance: { hi: "हाज़िरी", en: "Attendance" },
  gradeScale: { hi: "ग्रेड कैसे बनता है", en: "How grades work" },
  passNote: { hi: "हर विषय में पास होने के लिए कम से कम", en: "To pass each subject, at least" },
  resultError: { hi: "रिज़ल्ट अभी नहीं खुल रहा। थोड़ी देर बाद देखें।", en: "The result can't be opened right now. Please try later." },
} as const;
